name: Log Time Job

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  log_time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Run logging script
        run: |
          chmod +x log_time.sh
          ./log_time.sh

      - name: Run log count script
        run: |
          chmod +x count_logs.sh
          ./count_logs.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "ArenJohnD"
          git config --global user.email "esoen.arenjohn@gmail.com"
          git add log.txt log_count.txt
          git commit -m "Update log and count files" || echo "No changes to commit"
          git push
